default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: howwasit_development

test:
  <<: *default
  database: howwasit_test

production:
  <<: *default
  database: howwasit_production
  username: howwasit
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
